(function(){/* 
 
 Copyright The Closure Library Authors. 
 SPDX-License-Identifier: Apache-2.0 
*/ 
'use strict';var m=this||self;function aa(a,b,c){return a.call.apply(a.bind,arguments)}function ba(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var e=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(e,d);return a.apply(b,e)}}return function(){return a.apply(b,arguments)}} 
function n(a,b,c){Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?n=aa:n=ba;return n.apply(null,arguments)};function ca(a,b){Array.prototype.forEach.call(a,b,void 0)};function p(a){p[" "](a);return a}p[" "]=function(){};var ha={},r=null;var ia="function"===typeof Uint8Array;function ja(a){return null!==a&&"object"==typeof a&&!Array.isArray(a)&&!(ia&&null!=a&&a instanceof Uint8Array)}function ka(a,b){if(null!=a)return Array.isArray(a)||ja(a)?la(a,b):b(a)}function la(a,b){if(Array.isArray(a)){var c=Array(a.length);for(var d=0;d<a.length;d++)c[d]=ka(a[d],b);Array.isArray(a)&&a[ma]&&na(c);return c}c={};for(d in a)c[d]=ka(a[d],b);return c} 
function oa(a){switch(typeof a){case "number":return isFinite(a)?a:String(a);case "object":if(ia&&null!=a&&a instanceof Uint8Array){var b;void 0===b&&(b=0);if(!r){r={};for(var c="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".split(""),d=["+/=","+/","-_=","-_.","-_"],e=0;5>e;e++){var f=c.concat(d[e].split(""));ha[e]=f;for(var g=0;g<f.length;g++){var h=f[g];void 0===r[h]&&(r[h]=g)}}}b=ha[b];c=Array(Math.floor(a.length/3));d=b[64]||"";for(e=f=0;f<a.length-2;f+=3){var l=a[f],k=a[f+1]; 
h=a[f+2];g=b[l>>2];l=b[(l&3)<<4|k>>4];k=b[(k&15)<<2|h>>6];h=b[h&63];c[e++]=g+l+k+h}g=0;h=d;switch(a.length-f){case 2:g=a[f+1],h=b[(g&15)<<2]||d;case 1:a=a[f],c[e]=b[a>>2]+b[(a&3)<<4|g>>4]+h+d}a=c.join("")}return a;default:return a}}const ma=Symbol("IS_REPEATED_FIELD");function na(a){Array.isArray(a)&&!Object.isFrozen(a)&&(a[ma]=!0);return a};let u;function y(a){var b=u;u=null;a||(a=b);b=this.constructor.messageId;a||(a=b?[b]:[]);this.i=b?0:-1;this.g=a;a:{b=this.g.length;a=b-1;if(b&&(b=this.g[a],ja(b))){this.l=a-this.i;this.j=b;break a}this.l=Number.MAX_VALUE}}Object.freeze(na([]));function z(a,b){return-1===b?null:b>=a.l?a.j?a.j[b]:void 0:a.g[b+a.i]}function C(a,b,c){a=z(a,b);return null==a?c:a}function D(a,b){a=z(a,b);a=null==a?a:!!a;return null==a?!1:a}function pa(a){a=z(a,13);a=null==a?a:+a;return null==a?0:a} 
y.prototype.toJSON=function(){return la(this.g,oa)};function qa(a){var b=ra;u=a=a?JSON.parse(a):null;b=new b(a);u=null;return b}y.prototype.toString=function(){return this.g.toString()};var ra=class extends y{};function sa(a=window){return a};var ta=document,E=window;/* 
 
 SPDX-License-Identifier: Apache-2.0 
*/ 
function F(a,b,c){a.addEventListener&&a.addEventListener(b,c,!1)}function G(a,b,c){a.removeEventListener&&a.removeEventListener(b,c,!1)};var ua=RegExp("^(?:([^:/?#.]+):)?(?://(?:([^\\\\/?#]*)@)?([^\\\\/?#]*?)(?::([0-9]+))?(?=[\\\\/?#]|$))?([^?#]+)?(?:\\?([^#]*))?(?:#([\\s\\S]*))?$");function H(a){try{var b;if(b=!!a&&null!=a.location.href)a:{try{p(a.foo);b=!0;break a}catch(c){}b=!1}return b}catch(c){return!1}}function va(a,b){if(a)for(const c in a)Object.prototype.hasOwnProperty.call(a,c)&&b.call(void 0,a[c],c,a)}let I=[];const J=()=>{const a=I;I=[];for(const b of a)try{b()}catch(c){}}; 
var wa=(a,b)=>{"complete"===a.readyState||"interactive"===a.readyState?(I.push(b),1==I.length&&(window.Promise?Promise.resolve().then(J):window.setImmediate?setImmediate(J):setTimeout(J,0))):a.addEventListener("DOMContentLoaded",b)};function xa(a){a=void 0===a?document:a;var b="IMG";let c;"application/xhtml+xml"===(null==(c=a)?void 0:c.contentType)&&(b=b.toLowerCase());return a.createElement(b)};function L(a,b,c=null){ya(a,b,c)}function ya(a,b,c){a.google_image_requests||(a.google_image_requests=[]);const d=xa(a.document);if(c){const e=f=>{c&&c(f);G(d,"load",e);G(d,"error",e)};F(d,"load",e);F(d,"error",e)}d.src=b;a.google_image_requests.push(d)};let za=0;function Aa(a){return(a=Ba(a,document.currentScript))&&a.getAttribute("data-jc-version")||"unknown"}function Ba(a,b=null){return b&&b.getAttribute("data-jc")===String(a)?b:document.querySelector(`[${"data-jc"}="${a}"]`)} 
function Ca(){if(!(.01<Math.random())){var a=`https://${"pagead2.googlesyndication.com"}/pagead/gen_204?id=jca&jc=${24}&version=${Aa(24)}&sample=${.01}`,b=window,c;if(c=b.navigator)c=b.navigator.userAgent,c=/Chrome/.test(c)&&!/Edge/.test(c)?!0:!1;c&&b.navigator.sendBeacon?b.navigator.sendBeacon(a):L(b,a)}};var Da=a=>a.innerHeight>=a.innerWidth?0:90,Ea=!!window.google_async_iframe_id;let M=Ea&&window.parent||window;class Fa{constructor(a,b){this.error=a;this.context=b.context;this.msg=b.message||"";this.id=b.id||"jserror";this.meta={}}};const Ga=RegExp("^https?://(\\w|-)+\\.cdn\\.ampproject\\.(net|org)(\\?|/|$)");var Ha=class{constructor(a,b){this.g=a;this.i=b}},Ma=class{constructor(a,b){this.url=a;this.T=!!b;this.depth=null}};function N(a,b){const c={};c[a]=b;return[c]}function Na(a,b,c,d,e){const f=[];va(a,function(g,h){(g=Oa(g,b,c,d,e))&&f.push(h+"="+g)});return f.join(b)} 
function Oa(a,b,c,d,e){if(null==a)return"";b=b||"&";c=c||",$";"string"==typeof c&&(c=c.split(""));if(a instanceof Array){if(d=d||0,d<c.length){const f=[];for(let g=0;g<a.length;g++)f.push(Oa(a[g],b,c,d+1,e));return f.join(c[d])}}else if("object"==typeof a)return e=e||0,2>e?encodeURIComponent(Na(a,b,c,d,e+1)):"...";return encodeURIComponent(String(a))}function Pa(a){let b=1;for(const c in a.i)b=c.length>b?c.length:b;return 3997-b-a.j.length-1} 
function Qa(a,b,c){b=b+"//pagead2.googlesyndication.com"+c;let d=Pa(a)-c.length;if(0>d)return"";a.g.sort(function(f,g){return f-g});c=null;let e="";for(let f=0;f<a.g.length;f++){const g=a.g[f],h=a.i[g];for(let l=0;l<h.length;l++){if(!d){c=null==c?g:c;break}let k=Na(h[l],a.j,",$");if(k){k=e+k;if(d>=k.length){d-=k.length;b+=k;e=a.j;break}c=null==c?g:c}}}a="";null!=c&&(a=e+"trn="+c);return b+a}class O{constructor(){this.j="&";this.i={};this.l=0;this.g=[]}};function P(a,b,c,d,e,f){if((d?a.g:Math.random())<(e||.01))try{let g;c instanceof O?g=c:(g=new O,va(c,(l,k)=>{var q=g,t=q.l++;l=N(k,l);q.g.push(t);q.i[t]=l}));const h=Qa(g,a.i,"/pagead/gen_204?id="+b+"&");h&&("undefined"!==typeof f?L(m,h,f):L(m,h))}catch(g){}}class Ra{constructor(){var a=void 0===a?E:a;this.i="http:"===a.location.protocol?"http:":"https:";this.g=Math.random()}};let Q=null;var Sa=()=>{const a=m.performance;return a&&a.now&&a.timing?Math.floor(a.now()+a.timing.navigationStart):Date.now()},Ta=()=>{const a=m.performance;return a&&a.now?a.now():null};class Ua{constructor(a,b){var c=Ta()||Sa();this.label=a;this.type=b;this.value=c;this.duration=0;this.uniqueId=Math.random();this.slotId=void 0}};const R=m.performance,Va=!!(R&&R.mark&&R.measure&&R.clearMarks),T=function(a){let b=!1,c;return function(){b||(c=a(),b=!0);return c}}(()=>{var a;if(a=Va){var b;if(null===Q){Q="";try{a="";try{a=m.top.location.hash}catch(c){a=m.location.hash}a&&(Q=(b=a.match(/\bdeid=([\d,]+)/))?b[1]:"")}catch(c){}}b=Q;a=!!b.indexOf&&0<=b.indexOf("1337")}return a});function Wa(a){a&&R&&T()&&(R.clearMarks(`goog_${a.label}_${a.uniqueId}_start`),R.clearMarks(`goog_${a.label}_${a.uniqueId}_end`))} 
class Xa{constructor(){var a=U;this.events=[];this.i=a||m;let b=null;a&&(a.google_js_reporting_queue=a.google_js_reporting_queue||[],this.events=a.google_js_reporting_queue,b=a.google_measure_js_timing);this.g=T()||(null!=b?b:1>Math.random())}start(a,b){if(!this.g)return null;a=new Ua(a,b);b=`goog_${a.label}_${a.uniqueId}_start`;R&&T()&&R.mark(b);return a}end(a){if(this.g&&"number"===typeof a.value){a.duration=(Ta()||Sa())-a.value;var b=`goog_${a.label}_${a.uniqueId}_end`;R&&T()&&R.mark(b);!this.g|| 
2048<this.events.length||this.events.push(a)}}};function Ya(a){let b=a.toString();a.name&&-1==b.indexOf(a.name)&&(b+=": "+a.name);a.message&&-1==b.indexOf(a.message)&&(b+=": "+a.message);if(a.stack){a=a.stack;try{-1==a.indexOf(b)&&(a=b+"\n"+a);let c;for(;a!=c;)c=a,a=a.replace(/((https?:\/..*\/)[^\/:]*:\d+(?:.|\n)*)\2/,"$1");b=a.replace(/\n */g,"\n")}catch(c){}}return b} 
function Za(a,b,c){let d,e;try{a.g&&a.g.g?(e=a.g.start(b.toString(),3),d=c(),a.g.end(e)):d=c()}catch(f){c=!0;try{Wa(e),c=a.m(b,new Fa(f,{message:Ya(f)}),void 0,void 0)}catch(g){a.J(217,g)}if(c){let g,h;null==(g=window.console)||null==(h=g.error)||h.call(g,f)}else throw f;}return d}function $a(a,b){var c=V;return(...d)=>Za(c,a,()=>b.apply(void 0,d))} 
class ab{constructor(){var a=bb;this.j=W;this.i=null;this.m=this.J;this.g=void 0===a?null:a;this.l=!1}pinger(){return this.j}J(a,b,c,d,e){e=e||"jserror";let f;try{const v=new O;var g=v;g.g.push(1);g.i[1]=N("context",a);b.error&&b.meta&&b.id||(b=new Fa(b,{message:Ya(b)}));if(b.msg){g=v;var h=b.msg.substring(0,512);g.g.push(2);g.i[2]=N("msg",h)}var l=b.meta||{};b=l;if(this.i)try{this.i(b)}catch(A){}if(d)try{d(b)}catch(A){}d=v;l=[l];d.g.push(3);d.i[3]=l;d=m;l=[];b=null;do{var k=d;if(H(k)){var q=k.location.href; 
b=k.document&&k.document.referrer||null}else q=b,b=null;l.push(new Ma(q||""));try{d=k.parent}catch(A){d=null}}while(d&&k!=d);for(let A=0,Ia=l.length-1;A<=Ia;++A)l[A].depth=Ia-A;k=m;if(k.location&&k.location.ancestorOrigins&&k.location.ancestorOrigins.length==l.length-1)for(q=1;q<l.length;++q){var t=l[q];t.url||(t.url=k.location.ancestorOrigins[q-1]||"",t.T=!0)}var w=l;let S=new Ma(m.location.href,!1);k=null;const da=w.length-1;for(t=da;0<=t;--t){var x=w[t];!k&&Ga.test(x.url)&&(k=x);if(x.url&&!x.T){S= 
x;break}}x=null;const sb=w.length&&w[da].url;0!=S.depth&&sb&&(x=w[da]);f=new Ha(S,x);if(f.i){w=v;var B=f.i.url||"";w.g.push(4);w.i[4]=N("top",B)}var ea={url:f.g.url||""};if(f.g.url){var fa=f.g.url.match(ua),K=fa[1],Ja=fa[3],Ka=fa[4];B="";K&&(B+=K+":");Ja&&(B+="//",B+=Ja,Ka&&(B+=":"+Ka));var La=B}else La="";K=v;ea=[ea,{url:La}];K.g.push(5);K.i[5]=ea;P(this.j,e,v,this.l,c)}catch(v){try{P(this.j,e,{context:"ecmserr",rctx:a,msg:Ya(v),url:f&&f.g.url},this.l,c)}catch(S){}}return!0}};class cb{};let W,V;if(Ea&&!H(M)){let a="."+ta.domain;try{for(;2<a.split(".").length&&!H(M);)ta.domain=a=a.substr(a.indexOf(".")+1),M=window.parent}catch(b){}H(M)||(M=window)}const U=M,bb=new Xa;var db=()=>{if(!U.google_measure_js_timing){var a=bb;a.g=!1;a.events!=a.i.google_js_reporting_queue&&(T()&&ca(a.events,Wa),a.events.length=0)}};W=new Ra;"number"!==typeof U.google_srt&&(U.google_srt=Math.random());var eb=W,fb=U.google_srt;0<=fb&&1>=fb&&(eb.g=fb);V=new ab; 
V.i=a=>{const b=za;0!==b&&(a.jc=String(b),a.shv=Aa(b))};V.l=!0;"complete"==U.document.readyState?db():bb.g&&F(U,"load",()=>{db()});var X=(a,b)=>$a(a,b),gb=(a,b,c)=>{var d=cb,e="R";d.R&&d.hasOwnProperty(e)||(e=new d,d.R=e);d=[];!b.eid&&d.length&&(b.eid=d.toString());P(W,a,b,!0,c,void 0)};function Y(a,b,c={}){c.msg_type=b;c.googMsgType="sth";b=JSON.stringify(c);a.parent.postMessage(b,"*")}function hb(a){if(a.C||D(a.i,2))return!0;let b=!0;const c=ib(a);c&&(b=36E5<=c);if(b)try{a.g.localStorage.removeItem("LAST_INTERSTITIAL_TIME")}catch(d){}return b}function Z(a,b,c){C(a.i,3,"")&&(b.qid=C(a.i,3,""));C(a.i,10,"")&&(b.eid=C(a.i,10,""));b.req=E.location.href;gb(a.L(),b,c)} 
function ib(a){try{const b=+a.g.localStorage.getItem("LAST_INTERSTITIAL_TIME"),c=Date.now();if(b&&b<c)return c-b}catch(b){}return null} 
class jb{constructor(a,b){this.g=E;this.j=a;this.o=!1;this.u=null;this.m=0;this.i=b;this.C=D(this.i,11)||10===C(this.i,12,0)||11===C(this.i,12,0)}L(){}F(){if(this.o=hb(this))this.G(),C(this.i,1,"")&&this.g.parent.postMessage(C(this.i,1,""),"*")}s(){if(!this.m){this.u&&G(this.g,"storage",this.u);this.m=Date.now();if(!D(this.i,2)&&!this.C)try{this.g.localStorage.setItem("LAST_INTERSTITIAL_TIME",""+this.m)}catch(b){}this.P();if(this.j){var a=this.g.document.createEvent("Event");a.initEvent("i-creative-view", 
!0,!1);this.j.dispatchEvent(a);a=this.g.document.createEvent("Event");a.initEvent("onshow",!0,!1);this.g.dispatchEvent(a)}}}G(){this.g.IntersectionObserver&&.01<pa(this.i)?(new this.g.IntersectionObserver((a,b)=>{a.forEach(c=>{if(!(0>=c.intersectionRatio)){this.s();for(const d of this.j.document.getElementsByClassName("GoogleActiveViewElement"))d.removeAttribute("data-google-av-dm");b.disconnect()}})},{threshold:pa(this.i)})).observe(this.g.document.documentElement):F(this.g,"message",X(262,a=>{a:{if(a&& 
(this.g.parent==a.source||this.g.parent.parent==a.source)){var b={};try{b=this.g.JSON.parse(a.data)}catch(c){a=void 0;break a}"i-view"==(b&&b.msg_type)&&this.o&&this.s()}a=void 0}return a}));this.C||(this.u=X(263,()=>{this.o=hb(this);if(!this.o){var a={["i_tslv"]:ib(this)};Y(this.g,"i-no",a)}}),F(this.g,"storage",this.u));Y(this.g,"i-adframe-load")}P(a){let b;try{const c=sa(this.j);c.vv?c.vv():b=!0}catch(c){V.J(533,c,void 0,void 0);return}a=a||1;b?(Z(this,{vf:a}),3<=a||this.g.setTimeout(n(jb.prototype.P, 
this,a+1),3E3)):1<a&&Z(this,{vs:a})}};class kb{constructor(){this.promise=new Promise(a=>{this.g=a})}};var lb=class{constructor(){const a=new kb;this.promise=a.promise;this.resolve=a.g}};function mb(a){window.parent.postMessage(JSON.stringify({type:"rewarded",message:a}),"*")};var nb=a=>{a=a.document;let b={};a&&(b="CSS1Compat"==a.compatMode?a.documentElement:a.body);return b||{}};function ob(a,b,c){gb("jserror",{context:"iaf::itf",req:E.location.href,db:a?1:0,ls:b?1:0,eid:C(c,10,""),qid:C(c,3,""),rtype:C(c,12,0)})}function pb(a,b){qb(a,b)&&(a.l.style.background="rgba(192,192,192, .3)",m.setTimeout(()=>{a.l.style.background="transparent";a.dismiss(2)},750))}function rb(a,b){let c;b.some(d=>"intervention"===d.type&&"HeavyAdIntervention"===(null==(c=d.body)?void 0:c.id))&&(Z(a,{hai:"1"},1),a.m?a.dismiss(8):Y(a.g,"i_iif"))} 
function tb(a){var b=a.l.getBoundingClientRect(),c=b.bottom,d=b.right;const e=nb(a.g).clientHeight,f=nb(a.g).clientWidth,g=Math.floor(c-e),h=Math.floor(d-f);if(0<=g||5<h)c-=b.top,d-=b.left,b=a.g,Z(a,{dhb:g>=c?1:0,dhr:h>=d?1:0,h:e,w:f,bh:c,bw:d,opb:g,opr:h,pt:b.innerHeight>=b.innerWidth?1:0,req:a.g.location.href})}function ub(a){const b=X(259,n(function(){Y(this.g,"i-blur");G(this.g,"blur",b)},a));F(a.g,"blur",b)}function vb(a,b){var c={};D(a.i,15)?(mb("canceled"),mb("closed")):Y(a.g,b,c)} 
function wb(a,b){const c=a.g.document.getElementById("creative");a.g.goog_vignette_survey&&(a.g.goog_vignette_survey.display(c,()=>{a.dismiss(3)},()=>{},1),b&&b.stopPropagation())}function xb(a){!1===a.A&&a.enableDismissListeners();a.O&&F(a.O,"click",X(261,c=>wb(a,c)));const b=a.g.document.getElementById("card");b&&b.addEventListener("click",X(909,c=>{null==c||c.stopPropagation()}))}function yb(a){F(a.g,"resize",()=>{const b=Da(a.g);a.D?(a.D=!1,a.I=90===b):(a.I?0===b:90===b)&&a.dismiss(4)})} 
function zb(a){var b=X(617,c=>{var d=document.activeElement;2==C(a.i,5,0)&&(d=a.j.document.activeElement);(27===c.which||13===c.which&&d===a.l)&&a.dismiss(5);if(9===c.which){var e=Ab(a);d=Array.prototype.indexOf.call(e,d,void 0);e=Bb.length;const f=Ab(a);c.shiftKey&&0===d?(c.preventDefault(),f[e-1].focus()):c.shiftKey||d!==e-1||(c.preventDefault(),f[0].focus())}});F(a.g,"keydown",b);2===C(a.i,5,0)&&F(a.j,"keydown",b);b=Ab(a).filter((c,d)=>{c||Z(a,{missingFocusableChild:1,index:d});return!!c});ca(b, 
(c,d)=>{c.setAttribute("tabindex",d+1)});b.length&&b[0].focus()}function Cb(a){a.g.addEventListener("message",b=>{if(b.source===a.j)try{const c=JSON.parse(b.data);"rewarded"===c.type&&"closed"===c.message&&a.dismiss(11===C(a.i,12,0)?6:1)}catch(c){}})}function Ab(a){return 2===C(a.i,5,0)?Db.map(b=>a.j.document.getElementById(b)):Bb.map(b=>document.getElementById(b))} 
function qb(a,b){if(!b)return!0;if((b.preventDefault?b.defaultPrevented:!1===b.returnValue)||b.target&&b.target.ownerDocument==a.j.document)return!1;for(a=b.target;a;){if("creative"==a.id)return!1;a=a.parentElement}return!0} 
class Eb extends jb{constructor(a,b,c,d){super(a,d);this.l=b;this.O=c;this.K=0;this.N=X(260,e=>{this.dismiss(1);e&&e.stopPropagation()});this.M=e=>pb(this,e);this.H=[];this.B=[];this.D=this.I=this.A=!1;this.v=null}F(){super.F();(this.v=this.g.ReportingObserver?new this.g.ReportingObserver((a,b)=>{rb(this,a)&&b.disconnect()},{buffered:!0}):null)&&F(this.g,"unload",()=>{rb(this,this.v.takeRecords());this.v.disconnect()})}L(){return"ia_evt"}addViewListener(a){a=$a(483,a);this.m?a():this.H.push(a)}addDismissListener(a){this.B.push($a(484, 
a))}disableDismissListeners(){this.A=!0;G(this.l,"click",this.N);G(this.g.document,"click",this.M)}enableDismissListeners(){this.A=!1;F(this.l,"click",this.N);F(this.g.document,"click",this.M)}dismiss(a){document.body.setAttribute("aria-hidden","true");Z(this,{ttd:Date.now()-this.m,req:E.location.href,pda:this.K,ds:a,rtype:C(this.i,12,0),idrw:D(this.i,15)?1:0});this.K++||ub(this);let b=0;for(let d=0;d<this.B.length;d++)b=Math.max(b,this.B[d]());b=Math.min(b,1E3);let c="i-dismiss";6===a?c="r-dismiss-before-reward": 
7===a&&(c="r-dismiss-after-reward");0===b?vb(this,c):m.setTimeout(()=>vb(this,c),b)}G(){super.G();xb(this)}s(){super.s();this.I=90===Da(this.g);this.D=0===this.g.innerWidth&&0===this.g.innerHeight;this.l.setAttribute("aria-label",C(this.i,7,""));yb(this);Za(V,772,()=>zb(this));tb(this);document.getElementById("ad_iframe").contentWindow.postMessage(JSON.stringify({type:"rewarded",message:"visible"}),"*");for(let a=0;a<this.H.length;a++)this.H[a]();Cb(this);Ca()}} 
var Bb=["dismiss-button","creative"],Db=["dismiss-button","creative-content"];za=24;const Fb=Ba(24,document.currentScript);if(null==Fb)throw Error("JSC not found 24");const Gb={},Hb=Fb.attributes;for(let a=Hb.length-1;0<=a;a--){const b=Hb[a].name;0===b.indexOf("data-jcp-")&&(Gb[b.substring(9)]=Hb[a].value)} 
(function(a){const b=qa(a.config);a=X(258,()=>{{var c=document.getElementById("ad_iframe").contentWindow;var d=E.document;const f=c.document,g=C(b,5,0);var e=0===g||2===g?f.getElementById(C(b,6,"")):d.getElementById(C(b,6,""));d=0===g?f.getElementById(C(b,8,"")):d.getElementById(C(b,8,""));let h;try{h=!!E.localStorage}catch(l){}e?(h||ob(e,h,b),c=new Eb(c,e,d,b),c.F()):(ob(e,h,b),Y(E,"i_iif"),c=null)}window.interstitialAdFrame=c;e=window;e.google_llp||(e.google_llp={});e=e.google_llp;e[9]||(e[9]=new lb); 
e[9].resolve(c);return c});if(0===C(b,5,0)||2===C(b,5,0)||D(b,16)){const c=document.getElementById("ad_iframe");null!=c.contentDocument?wa(c.contentDocument,a):document.getElementById("ad_iframe").addEventListener("load",a)}else a()})(Gb);}).call(this);
